### ISSUE TITLE
Snapshotting Errors

### ISSUE THREAD

**Issue by bbonenfant** [MORSECorp/snappiershot#46]
## Feature
Create an api for that is similar to the `pytest.raises` where an error that is raised is snapshotted. This can provide users with an easier method of testing the contents of raised errors (without having to mess with regex expressions or hardcoding) as well as allow the user to see what their error messages will look like.

## Proposal
```python
def flaky_function():
    raise ValueError("Don't trust this function")

def test_flaky_function(snapshot):
    with snapshot.raises():    # Maybe we allow the user to provide the expected type, although I don't think that's necessary
        flaky_function()
    # Test passed.
    # Snapshot of {"__snappiershot_raises__": "ValueError", "args": ["Don't trust this function"]}
```

**Comment by lenabradley** [comment]
I agree that we should support error snapshotting. There's a strong use case for that. 

To be clear, the alternatives (i.e. non-snapshot ways of dealing with testing errors) are:
1. check the _type_ of error raised e.g. `ValueError` in `pytest.raises(ValueError)`.
    - pros: flexible to non-meanginful changes in the error message itself; easy to write/maintain the test
    - cons: you may catch the _wrong_ value error! (e.g. a value error raised from somewhere you don't intend to test)
1. check both the type and contents of the error raised (e.g. `pytest.raises(ValueError, match="Don't trust this function")
    - pros: (almost) guarantees you're catching the correct error, can also use regex for the "match"
    - cons: need to copy-paste the error message into the test, difficult to write/maintain the test


Having snapshot support would be better than both of the above options (gets both pros)
