### ISSUE TITLE
Support for Path type

### ISSUE THREAD

**Issue by bbonenfant** [MORSECorp/snappiershot#53]
How should we support [pathlib.Path](https://docs.python.org/3/library/pathlib.html#pathlib.Path) objects? Should we stringify them and treat them as files?

## Examples
```python
encode_path_option_1(Path("/path/to/file")) == "/path/to/file"
```

```python
encode_path_option_2(Path("/path/to/file")) == {"__snappiershot_path__": "Path", "value": "/path/to/file"}
```

```python
encode_path_option_3(Path("/path/to/file")) == {"__snappiershot_path__": "Path", "parts": ["/", "path", "to", "file"]}
```

```python
encode_path_option_3(Path("/path/to/file")) == {"__snappiershot_path__": "Path", "contents": "contents of file", "exists": True, "parts": ["/", "path", "to", "file"]}
```

**Comment by lenabradley** [comment]
Some comments:
* Option 1: I appreciate the simplicity but it does not allow us to properly differentiate `str`-paths from `Path`-paths, so I think we have to nix it on those grounds, unfortunately
* Option 2: i like the simplicity
* Option 3: I dislike the long form (more complex) but it is nicer for diff-ing and may be safer for OS-agnostic operations (more comments below)
* Option 3 (aka option 4): I definitely don't think we should do this. if we're snapshotting the path, we shoudl snapshot the path; the path is the name of the file, the path is not the file. https://en.wikipedia.org/wiki/Haddocks%27_Eyes


Also, we should consider OS-specific pathing or, ideally, avoid it altogether (i.e. `Path` vs the derived `PosixPath` and `WindowsPath`). Some discussion here: https://realpython.com/python-pathlib/#paths-as-proper-objects. Seems like the string-conversion will depend upon the system/OS where the code was executed which could be an issue. Option 3 (the first) could be more robust to this.

**Comment by bbonenfant** [comment]
I agree with everything you said, it sounds like Option 3 it is!

**Comment by ysmolyar** [comment]
When attempting to instantiate a `pathlib.WindowsPath` object on a Mac, pathlib throws `NotImplementedError: cannot instantiate 'WindowsPath' on your system`.

1.  Is it possible that a Windows user will snapshot a PosixPath, or a Posix user will snapshot a WindowsPath?
2. Is there a good way for us to test this in an OS-agnostic way?
