### ISSUE TITLE
Support pandas Dataframe

### ISSUE THREAD

**Issue by bbonenfant** [MORSECorp/snappiershot#55]
We should support this popular type. Blocked by #25

**Comment by lenabradley** [comment]
Question: I assume we don't want to enforce pandas as a dependency unless the user needs it for asserting DFs. Any thoughts about the best way to deal with that? I imagine this will happen with other custom types/dependencies as well, so we should setup a good, repeatable process. Similarly, will have to make sure that if there are multiple such optional dependencies, that their versions do not conflict and are sufficiently broad/flexible.

**Comment by bbonenfant** [comment]
We can do some import slewing to handle `pandas` and `numpy` objects. This is the example I go to from the `pytest` code:
```python
def _is_numpy_array(obj: object) -> bool:
    """Return true if the given object is a numpy array.

    A special effort is made to avoid importing numpy unless it's really necessary.
    """
    import sys

    np = sys.modules.get("numpy")  # type: Any
    if np is not None:
        return isinstance(obj, np.ndarray)
    return False
```
