### ISSUE TITLE
[BUG] Pandas dataframe snapshots are abbreviated

### ISSUE THREAD

**Issue by IkeKap** [MORSECorp/snappiershot#83]
**Describe the bug**
A snapshot of a pandas dataframe is abbreviated with ... instead of showing the complete dataframe

**To Reproduce**
Snapshot a large dataframe (my issue occurred with one 16 * 8 dataframe)

**Expected behavior**
The snapshot to contain the entire data without any abbreviations

**Screenshots**
<img width="581" alt="image" src="https://user-images.githubusercontent.com/24295451/110164629-9e1f2980-7dbf-11eb-9aac-a566c28afed1.png">

<img width="577" alt="image" src="https://user-images.githubusercontent.com/24295451/110164793-dd4d7a80-7dbf-11eb-9c1c-c162494f774c.png">

**Versions:**
 - Python version: 3.7
 - Snappiershot version: 1.0.0

**Comment by Conniemac** [comment]
@IkeKap I think this is a matter of print formatting. Just to confirm is the screenshot you posted from calling `print(df)`? I made a similar data frame (4 rows x 10 columns). I checked the json file that was produced by storing that data frame as a snap shot and it appears all the data is stored correctly. The code calls `df.to_dict()` then stores the resulting dictionary in a json file. 

These are screen shots from the json file that is stored by the code. Each list is a row (4 rows in the data frame) and each list is 10 long (10 columns total).
<img width="291" alt="Screen Shot 2021-12-12 at 9 04 53 PM" src="https://user-images.githubusercontent.com/6226900/145742617-7ab39b3f-1fbd-49bd-a4ea-ed8afb86dd39.png">
<img width="212" alt="Screen Shot 2021-12-12 at 9 05 18 PM" src="https://user-images.githubusercontent.com/6226900/145742623-01229ef4-1be2-4e1e-87dc-7385a7a420dc.png">



If I call `print(df)` I see an abbreviated view like you posted. If I call `print(df.to_string())` I see all 10 columns printed.
Calling `print(df)`:
<img width="690" alt="Screen Shot 2021-12-12 at 9 04 18 PM" src="https://user-images.githubusercontent.com/6226900/145742253-147048f2-f6b3-471f-8c32-3be6d2531771.png">

Calling `print(df.to_string()`:
<img width="1192" alt="Screen Shot 2021-12-12 at 9 19 17 PM" src="https://user-images.githubusercontent.com/6226900/145742382-d00d62d9-fa7c-4f02-bccd-db4a48bff6be.png">
<img width="454" alt="Screen Shot 2021-12-12 at 9 19 24 PM" src="https://user-images.githubusercontent.com/6226900/145742394-bf56ccc9-bf18-46a0-9de8-832db3672598.png">

Just to be sure no data is missing I changed one of the values in column 3. This is one of the columns that is abbreviated in the screenshot above.

Let me know what you think.

**Comment by Conniemac** [comment]
I think this is just a print formatting issue so closing this for now. Feel free to re-open if I missed something.
